### ISSUE TITLE
-A option not handled correctly

### ISSUE THREAD

**Issue by scotts777** [frericksm/clj-windows#5]
when running clj with an -A  alias,  the :extra-deps for that alias definition is not being added to the classpath.  The below works on Mac OS X but not clj-windows.

clj -A:nrepl -m myisdb.db
or
clj -C:nrepl -m myisdb.db

:nrepl {:extra-deps {org.clojure/tools.nrepl {:mvn/version "0.2.13"}
                              refactor-nrepl/refactor-nrepl {:mvn/version "2.4.0"}
                              cider/cider-nrepl {:mvn/version "0.19.0-SNAPSHOT"}}}

**Comment by frericksm** [comment]
There is an issue  handling the -A option which may  affect you (see commit https://github.com/frericksm/clj-windows/commit/e3057a6328ac428b012326826e70cbb342434b5e
Despite this issue  
`clj -C:nrepl -m myisdb.db`  will not work since  your alias :nrepl  is not a make-classpath alias but a resolve-deps alias, so 
`clj -R:nrepl -m myisdb.db` should work for now 
(see https://clojure.org/guides/deps_and_cli#extra_deps) until the commit mentioned above will be released to a new version

**Comment by scotts777** [comment]
Yes you're right.  That worked.  
Thanks so much and thanks for making this tool for Windows devs.

**Comment by frericksm** [comment]
fixed in release 1.10.0.414.1
